---
title: "Himalayan treks"
author: "Basheer"
date: "2023-11-29"
categories: [news]

---

What is Hampta Pass Famous For
Make a trip here, offering a splendid view of two valleys. The trek gives you a strikingly contrasting view of Kullu and Lahaul Valley. Also, take a glimpse of the charming moon shaped Chandratal Lake. But first, hike through a steep, rocky, and vertical climb.

Every campsite has its charm!
Every campsite at trekking here, has its beauty. That can only be seen and felt by making a presence at a particular point. Enjoy the breathtaking sunset beyond Hanuman Tibba. Visible from the Bhalu ka Ghera campsite. Moreover, get a face-to-face view of the Deo Tibba peak.

Best Time To Visit Hampta Pass Trek
Snow is the main attraction of this trek. And the best time for hampta pass trek to see snow are June and July. The hampta pass temperature falls up to almost -15 degrees during this time. Those who are more of a green lover, the best time to visit hampta pass for lush landscapes is in the month of mid-July up till October. During this time the hampta pass weather is pleasant with just fresh snow.

Hampta Pass Trek Distance
The trek’s height is 14,100 ft. covering a Hampta pass distance of 35 km. During the trek’s length, you will journey through small forests. Witness different colors of blooming flowers as you ascend on the steep, vertical, and rocky inclines.

Hampta Pass Trek Difficult Level
This trek is doable for all ages. The trek difficulty level is easy to moderate. Including the chandratal lake trek difficulty. Making this trek, excellent for beginners. The entire trek is 5 Days and 4 Nights long. Make a visit to the famous moon lake from Chatru campsite.

Brief Itinerary of Hampta Pass Trek

Day 1: Arrive Jobra and Trek to Chika
The trek begins with a drive of 17 km (45 min) to Jobra, later trekking to Chika. The trail journeys through the forest of maple and pine trees. Hike with the Rani river flowing along your side. Meanwhile, passing through two wooden bridges and a soft patch of forest covering the walnut and oak trees.

Altitude: 10,100 ft
Trek: 4 km (2 hours)

Day 2: Chika to Bhalu ka Ghera
Wake up for the trek to Bhalu Ka Ghera, welcomed by the different colors of small flowers. Watch the snow melt and meet the river, as a bunch of mules graze on the lush grass. Enjoy the beautiful sunset behind the Hanuman Tibba peak, and retire for the day.

Altitude: 12,400 ft
Trek: 5 km (4 – 5 hours)

Day 3: Shea Goru via Hampta Pass
Hike through the mountains of Bhalu Ka Ghera and cross rockfall-prone areas. Later, climb vertically to reach here, altitude of 14,000 ft. Enjoy the bird’s-eye view of the Kullu and Lahaul valley, with Deo Tibba peak standing in front. Once done, head back to the campsite.

Altitude: 14,065 ft (Hampta Pass)
Trek: 5 km (7 – 8 hours)

Day 4: Shea Goru to Chatru, drive to Chandratal
Start your drive to Chatru campsite. Leave your luggage and get ready to visit Chandratal Lake. Soak in the beauty of the moon lake, and head back to the Chatru campsite, once done.

Altitude: 14,100 ft (Chandratal Lake)
Trek: 6 km (5 – 6 hours)

Day 5: Chatru to Manali drive
Wake up to the last morning of the hike. Pack your belongings for a return trip to Manali. Bid your goodbyes to the Spiti valley and drive back to Manali. Ending the Trek.

Drive: 65 km (2 -3 hours)

How To Reach Hampta Pass Trek Base Camp
The trek starts from Manali and is accessible via road.

Air:
Book a flight to Kullu and take a cab to Manali. You can also book a flight to Delhi or Chandigarh. Later, take a Volvo to Manali.

Road:
Take a Volvo ride available from Delhi as well as from Chandigarh.

Rail:
Take a train to Chandigarh railway station and from their book a private or shared cab to Manali.

Furthermore, the trek is a classic Himachal trip that has always attracted hikers. But if you are still craving more treks, then visit some nearby treks like- Rohtang Pass Trek and Beas Kund trek. Making your visit more memorable.


